name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Replace webhook placeholder
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        sed -i "s|WEBHOOK_PLACEHOLDER|$WEBHOOK_URL|g" script.js
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
